name: Update README Timestamp

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update timestamp in README.md
        run: |
          TIMESTAMP=$(date -u +"%A, %d %B %Y, %H:%M:%S %Z")
          sed -i "s|.*|\n    <em>Last checked for updates on: **${TIMESTAMP}**</em>\n    |" README.md

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: 🤖 Auto-update README timestamp"
            git push
          else
            echo "No changes to commit."
          fi
